# Generated by Django 5.1.5 on 2025-02-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg9', '0002_usercredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=20)),
                ('mileage', models.FloatField()),
                ('co2_emissions', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fuel_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdg9.carmodel'),
        ),
    ]
