# Generated by Django 5.1.5 on 2025-02-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdg9', '0003_auto_update_userprofile'),
        ('sdg9', '0003_carmodel_remove_userprofile_fuel_type_and_more'),
    ]

    operations = [
    ]
