# Generated by Django 5.1.5 on 2025-02-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdg9', '0004_merge_20250206_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vehicle_model',
        ),
    ]
